CREATE OR REPLACE VIEW ANALYTICS.TICKET_DAILY_VOLUME AS
SELECT
    DATE(created_at) AS ticket_date,
    COUNT(*) AS total_tickets
FROM AI.SUPPORT_TICKETS_ENRICHED
GROUP BY ticket_date;

CREATE OR REPLACE VIEW ANALYTICS.URGENCY_DISTRIBUTION AS
SELECT
    urgency,
    COUNT(*) AS total
FROM AI.SUPPORT_TICKETS_ENRICHED
GROUP BY urgency;

CREATE OR REPLACE VIEW ANALYTICS.SENTIMENT_TREND AS
SELECT
    DATE(created_at) AS ticket_date,
    sentiment,
    COUNT(*) AS total
FROM AI.SUPPORT_TICKETS_ENRICHED
GROUP BY ticket_date, sentiment;
